### ISSUE TITLE
Hash generation failed: Error: Failed to deserialize compiled model: invalid value: integer `2`, expected variant index 0 <= i < 2

### ISSUE THREAD

**Issue by tri2820** [zkonduit/ezkljs-engine#21]
When running the app https://ezkljs-engine.vercel.app/gen-witness with MNIST compiled model & input obtained here https://github.com/zkonduit/ezkljs-engine/tree/1b572b28ede906e73d7eee48be122bf571e14b80/public/data/mnist, error is shown as below
![image](https://github.com/zkonduit/ezkljs-engine/assets/22129923/b5f2b261-623a-47d6-abd3-017cfd56940a)

Same thing happens when trying to generate witness from these files on nodejs
```

/home/tri/whale/agentserve/node_modules/@ezkljs/engine/nodejs/ezkl.js:799
    const ret = new Error(getStringFromWasm0(arg0, arg1));
                ^


Error: Failed to deserialize compiled model: invalid value: integer `2`, expected variant index 0 <= i < 2
    at module.exports.__wbindgen_error_new (/home/tri/whale/agentserve/node_modules/@ezkljs/engine/nodejs/ezkl.js:799:17)
    at wasm://wasm/0102c642:wasm-function[2359]:0x3a100d
    at Object.module.exports.genWitness (/home/tri/whale/agentserve/node_modules/@ezkljs/engine/nodejs/ezkl.js:407:14)
    at <anonymous> (/home/tri/whale/agentserve/src/test.ts:18:31)

Node.js v21.1.0
```

**Comment by ethan-crypto** [comment]
This issue was patched with this PR: https://github.com/zkonduit/ezkljs-engine/pull/23

I forgot to update the new path to the artifacts from `data` to `data/1l_mlp`.
